server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db-changelog.xml

  freemarker:
    enabled: true
    template-loader-path: /WEB-INF/templates
    suffix: .ftl
  mail:
    host: smtp.gmail.com
    port: 587
    username: "r1ghtnowcp2@gmail.com"
    password: "vcuv icfd mzsx ewua"
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 5000
          wareTimeout: 5000
          starttls:
            enable: true

mail:
  sender: Test Application
  from: "${spring.mail.username}"
  subject: Please verify your accound
  content: "Dear $name, please follow the link below to verify your account: <a href=$url>ПЕРЕЙДИ ДА</a>"
  baseUrl: http://localhost:${server.port}

jwt:
  access:
    access: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
  refresh:
    access: "ZmVkY2JhOTg3NjU0MzIxMGZlZGNiYTk4NzY1NDMyMTA="
